ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/CityController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Localization;
using ReSalingTickets.Business.Entities;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.Models;
using System;
using System.Collections.Generic;

namespace ReSalingTickets.Presentation.Controllers
{
    public class CityController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _Resourcelocalizer;
        private ICityService _cityRepository;
        private readonly IMapper _mapper;
        
        public CityController(
            IStringLocalizer<SharedResource> Resourcelocalizer,
            IServiceFactory serviceFactory,
            IMapper mapper)
        {
            _mapper = mapper;
            _Resourcelocalizer = Resourcelocalizer;
            _cityRepository = serviceFactory.CreateCityService();
        }

        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult AddCity()
        {
            CityModel city = new CityModel();
            return View(city);
        }

        [HttpPost]
        public IActionResult AddCity(CityModel city)
        {
            if (ModelState.IsValid)
            {
                city.Id = Guid.NewGuid();
                _cityRepository.AddCity(_mapper.Map<CityDTO>(city));
            }
            return RedirectToAction("AdminPanel","User");
        }

        public IActionResult ShowAllCities()
        {
            var cc = _cityRepository.GetAllСities();
            var t = _mapper.Map<List<CityModel>>(cc);
            var cities = _mapper.Map<List<CityModel>>(_cityRepository.GetAllСities());
            return View(cities);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteCity(Guid id)
        {
            var city = _mapper.Map<CityModel>(_cityRepository.GetCity(id));
            return View(city);
        }

        [HttpPost]
        public IActionResult DeleteCity(CityModel city)
        {
            _cityRepository.DeleteCity(city.Id);
            return View();
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Views/City/AddCity.cshtml
@model ReSalingTickets.Presentation.Models.CityModel
@{
    ViewData["Title"] = "Contact";
}

<title>@ViewData["Title"] - ReSalingTickets</title>

@using (Html.BeginForm("AddCity", "City", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group text">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group text">
        <div class="col-md-offset-2 col-md-10 text">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>
}