ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/CityController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Localization;
using ReSalingTickets.Business.Entities;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.Models;
using System;
using System.Collections.Generic;

namespace ReSalingTickets.Presentation.Controllers
{
    public class CityController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _Resourcelocalizer;
        private ICityService _cityRepository;
        private readonly IMapper _mapper;
        
        public CityController(
            IStringLocalizer<SharedResource> Resourcelocalizer,
            IServiceFactory serviceFactory,
            IMapper mapper)
        {
            _mapper = mapper;
            _Resourcelocalizer = Resourcelocalizer;
            _cityRepository = serviceFactory.CreateCityService();
        }

        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult AddCity()
        {
            CityModel city = new CityModel();
            return View(city);
        }

        [HttpPost]
        public IActionResult AddCity(CityModel city)
        {
            if (ModelState.IsValid)
            {
                city.Id = Guid.NewGuid();
                _cityRepository.AddCity(_mapper.Map<CityDTO>(city));
            }
            return RedirectToAction("AdminPanel","User");
        }

        public IActionResult ShowAllCities()
        {
            var cc = _cityRepository.GetAllСities();
            var t = _mapper.Map<List<CityModel>>(cc);
            var cities = _mapper.Map<List<CityModel>>(_cityRepository.GetAllСities());
            return View(cities);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteCity(Guid id)
        {
            var city = _mapper.Map<CityModel>(_cityRepository.GetCity(id));
            return View(city);
        }

        [HttpPost]
        public IActionResult DeleteCity(CityModel city)
        {
            _cityRepository.DeleteCity(city.Id);
            return View();
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/EventController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.Models;
using ReSalingTickets.Presentation.ViewModels;
using Sakura.AspNetCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ReSalingTickets.Presentation.Controllers
{
    public class EventController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _Resourcelocalizer;
        private IEventService _eventService;
        private IVenueService _venueService;
        private readonly IMapper _mapper;

        public EventController(
            IStringLocalizer<SharedResource> Resourcelocalizer,
            IServiceFactory serviceFactory,
            IMapper mapper)
        {
            _mapper = mapper;
            _Resourcelocalizer = Resourcelocalizer;
            _eventService = serviceFactory.CreateEventService();
            _venueService = serviceFactory.CreateVenueService();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddEvent()
        {
            var model = new AddEventViewModel
            {
                Venues = GetAllVenues()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventViewModel eventModel, IFormFile file)
        {
            if (ModelState.IsValid && file != null && eventModel.Event.Date > DateTime.Now)
            {
                eventModel.Event.PathToTheBanner = ConvertToBase64(file);
                _eventService.AddEvent(_mapper.Map<Business.Entities.EventDTO>(eventModel.Event));
                return RedirectToAction("index", "Home");
            }
            else
            {
                var model = new AddEventViewModel
                {
                    Venues = GetAllVenues()
                };

                return View(model);
            }
        }

        [HttpGet]
        public IActionResult ShowAllEvents(string orderSort, string searchString, int? page)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(orderSort) ? "name" : "";
            ViewBag.CitySortParm = orderSort == "City" ? "city_desc" : "City";
            ViewBag.VenueSortParm = orderSort == "Venue" ? "venue_desc" : "Venue";
            ViewBag.VenueSortParm = orderSort == "Date" ? "date_desc" : "Date";

            var events = (from e in _eventService.GetAllShowEvent()
                         select e);
            switch (orderSort)
            {
                case "name":
                    events = events.OrderByDescending(s => s.Name);
                    break;
                case "City":
                    events = events.OrderBy(s => s.CityName);
                    break;
                case "city_desc":
                    events = events.OrderByDescending(s => s.CityName);
                    break;
                case "Venue":
                    events = events.OrderBy(s => s.VenueName);
                    break;
                case "venue_desc":
                    events = events.OrderByDescending(s => s.VenueName);
                    break;
                case "Date":
                    events = events.OrderBy(s => s.VenueName);
                    break;
                case "date_desc":
                    events = events.OrderByDescending(s => s.VenueName);
                    break;
                default:
                    events = events.OrderBy(s => s.Name);
                    break;
            }

            var newItems = _mapper.Map<List<EventShowModel>>(events);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var sss = newItems.ToPagedList(pageSize, pageNumber);
            return View(sss);
        }

        public IActionResult ShowDetalsEvent(Guid id)
        {
            var item = GetAllEvent().Find(x => x.Id.Equals(id));

            return View(item);
        }

        public List<EventShowModel> GetAllEvent()
        {
            return _mapper.Map<List<EventShowModel>>(_eventService.GetAllShowEvent());
        }

        public IEnumerable<SelectListItem> GetAllVenues()
        {
            var items = _venueService.GetAllVenues();

            var venues = items
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });

            return venues;
        }

        private static string ConvertToBase64(IFormFile file)
        {
            var t = ConvertToBase64(file);
            if (file == null)
            {
                return "Изображение отсутствует";
            }
            using (var fileStream = file.OpenReadStream())
            using (var ms = new MemoryStream())
            {
                fileStream.CopyTo(ms);
                var fileBytes = ms.ToArray();
                string s = Convert.ToBase64String(fileBytes);

                return s;
            }
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.Models;
using System;
using System.Threading.Tasks;

namespace ReSalingTickets.Presentation.Controllers
{
    public class UserController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _Resourcelocalizer;
        private UserManager<UserModel> _userManager;
        private ITicketService _ticketService;

        public UserController(
            IStringLocalizer<SharedResource> Resourcelocalizer,
            IServiceFactory serviceFactory)
        {
            _Resourcelocalizer = Resourcelocalizer;
            _userManager = serviceFactory.CreateUserManager();
            _ticketService = serviceFactory.CreateTicketService();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminPanel()
        {
            return View();
        }
        
        [Authorize]
        public IActionResult UserPanel()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _userManager.Users;
            return View(users);
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(user);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            return View(user);
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            UserModel user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ChagePassword(Guid id)
        {
            UserModel user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            ChagePasswordModel model = new ChagePasswordModel { id = Guid.Parse(user.Id), Login = user.UserName };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChagePassword(ChagePasswordModel item)
        {
            UserModel user = await _userManager.FindByIdAsync(item.id.ToString());
            if (user != null)
            {
                var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<UserModel>)) as IPasswordValidator<UserModel>;
                var _passwordHasher =
                    HttpContext.RequestServices.GetService(typeof(IPasswordHasher<UserModel>)) as IPasswordHasher<UserModel>;

                IdentityResult result =
                    await _passwordValidator.ValidateAsync(_userManager, user, item.NewPassword);
                if (result.Succeeded)
                {
                    user.PasswordHash = _passwordHasher.HashPassword(user, item.NewPassword);
                    await _userManager.UpdateAsync(user);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Пользователь не найден");
            }
            return View(item);
        }

        public async Task<IActionResult> Contact(Guid id)
        {
            var ticket = _ticketService.GetTicket(id);
            UserModel user = await _userManager.FindByIdAsync(ticket.SellerId.ToString());

            return View(user);
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/AdminPanel.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using ReSalingTickets.Presentation.Models.Enums
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="~/Scripts/jquery-2.1.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <div class="wrapper">
        <div id="tabs">
            <ul id="items">
                <li class="active"><a href="#tabs-1">@SharedLocalizer["МоиБилеты"]</a></li>
                <li><a href="#tabs-2">@SharedLocalizer["ОжидающиеПодтверждения"]</a></li>
                <li><a href="#tabs-3">@SharedLocalizer["Проданные"]</a></li>
                <li><a href="#tabs-4">@SharedLocalizer["МоиЗаказы"]</a></li>
            </ul>
        </div>
        <div class="tab-content">
            <div id="tabs-1" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.First, dbInfoModel = Model })
            </div>
            <div id="tabs-2" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Second, dbInfoModel = Model })
            </div>
            <div id="tabs-3" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Third, dbInfoModel = Model })
            </div>
            <div id="tabs-4" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Fourth, dbInfoModel = Model })
            </div>
        </div>
    </div>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script>
        $(function(){
            $('#tabs-1').show();

            $('#items li').click(function () {
                if($(this).attr('class')=='active'){
                    return false;
                }

                var prevActive = $('li.active').children().attr('href');
                var link = $(this).children().attr('href');
                $('li.active').removeClass('active');
                $(this).addClass('active');

                $(prevActive).fadeOut(500,function(){
                    $(link).fadeIn();

                    $('#items li').css('background', '#ccc');
                    $('li.active').css('background', '#f3f3f3');
                })
                return false;
            })
        });
    </script>
    <div class="form-horizontal">
        <ul>
            <li class="">
                <a a class="btn btn-sm btn-success" asp-controller="User" asp-action="Index">@SharedLocalizer["СписокПользователей"]</a>
                <a a class="btn btn-sm btn-success" asp-controller="Account" asp-action="AdminPanel">@SharedLocalizer["ПросмотрВсехСобытий"]</a>
                <a a class="btn btn-sm btn-success" asp-controller="City" asp-action="AddCity">@SharedLocalizer["Добавить Город"]</a>
                <a a class="btn btn-sm btn-success" asp-controller="Event" asp-action="AddEvent">@SharedLocalizer["Добавить событие"]</a>
                <a a class="btn btn-sm btn-success" asp-controller="Venue" asp-action="AddVenue">@SharedLocalizer["Добавить место проведения"]</a>
            </li>
        </ul>
    </div>
    <div class="form-inline">
        <ul>
            <li>
                <a class="btn btn-sm btn-primary" asp-controller="User" asp-action="Edit">@SharedLocalizer["ИзменитьЛичныеДанные"]</a>
            </li>
        </ul>
    </div>
</body>
</html>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/ChangePassword.cshtml
@model ReSalingTickets.Presentation.Models.ChagePasswordModel
@{
    ViewBag.Title = "Изменение пароля";
}
<h2>Изменение пароля для пользователя @Model.Login</h2>
<form asp-action="ChangePassword" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="id" />
    <input type="hidden" asp-for="Login" />

    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">Новый пароль</label>
        <input type="text" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/Contact.cshtml
@model ReSalingTickets.Presentation.Models.UserModel

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberPhone)
        </dd>
    </dl>
</div>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/Create.cshtml
@model ReSalingTickets.Presentation.Models.UserModel
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="Create" asp-controller="User">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Login" class="control-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя</label>
        <input type="text" asp-for="FirstName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия</label>
        <input type="text" asp-for="SecondName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Adress" class="control-label">Адресс</label>
        <input type="text" asp-for="Adress" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NumberPhone" class="control-label">Номер телефона</label>
        <input type="text" asp-for="NumberPhone" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="text" asp-for="Password" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-default" />
    </div>
</form>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/Edit.cshtml
@model ReSalingTickets.Presentation.Models.UserModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<form asp-action="Edit" method="post" asp-controller="User">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="PasswordHash" />
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="Locale" />
    </div>
    <div class="form-group">
        <label asp-for="Login" class="control-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя</label>
        <input type="text" asp-for="FirstName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия</label>
        <input type="text" asp-for="SecondName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Adress" class="control-label">Адресс</label>
        <input type="text" asp-for="Adress" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NumberPhone" class="control-label">Номер телефона</label>
        <input type="text" asp-for="NumberPhone" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/Index.cshtml
@model IEnumerable<ReSalingTickets.Presentation.Models.UserModel>
@{
    ViewBag.Title = "Список пользователей";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<a asp-action="Create">@SharedLocalizer["ДобавитьПользователя"]</a>

<table class="table">
    <tr><th>@SharedLocalizer["Логин"]</th><th>@SharedLocalizer["ДатаРегистрации"]</th><th></th></tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Login</td>
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="ChangePassword" asp-route-id="@user.Id">@SharedLocalizer["СменитьПароль"]</a>
                    <a class="btn btn-sm btn-primary" asp-controller ="Roles" asp-action="Edit" asp-route-id="@user.Id">@SharedLocalizer["ИзменитьПрава"]</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        @SharedLocalizer["Удалить"]
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/User/UserPanel.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Routing
@using ReSalingTickets.Presentation.ViewComponents
@using ReSalingTickets.Presentation.Models.Enums
@model ReSalingTickets.Presentation.Models.DbInfoModel
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="~/Scripts/jquery-2.1.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <div class="wrapper">
        <div id="tabs">
            <ul id="items">
                <li class="active text"><a href="#tabs-1">@SharedLocalizer["МоиБилеты"]</a></li>
                <li class="active text"><a href="#tabs-2">@SharedLocalizer["ОжидающиеПодтверждения"]</a></li>
                <li class="active text"><a href="#tabs-3">@SharedLocalizer["Проданные"]</a></li>
                <li class="active text"><a href="#tabs-4">@SharedLocalizer["МоиЗаказы"]</a></li>
            </ul>
        </div>
        <div class="tab-content fone">
            <div id="tabs-1" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.First, dbInfoModel = Model })
            </div>
            <div id="tabs-2" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Second, dbInfoModel = Model })
            </div>
            <div id="tabs-3" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Third, dbInfoModel = Model })
            </div>
            <div id="tabs-4" class="tabs-text">
                @await Component.InvokeAsync("TicketShowComponent", new { result = TubEnum.Fourth, dbInfoModel = Model })
            </div>
        </div>
    </div>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script>
        $(function(){
            $('#tabs-1').show();

            $('#items li').click(function () {
                if($(this).attr('class')=='active'){
                    return false;
                }

                var prevActive = $('li.active').children().attr('href');
                var link = $(this).children().attr('href');
                $('li.active').removeClass('active');
                $(this).addClass('active');

                $(prevActive).fadeOut(500,function(){
                    $(link).fadeIn();

                    $('#items li').css('background', '#ccc');
                    $('li.active').css('background', '#f3f3f3');
                })
                return false;
            })
        });
    </script>
    <div class="form-inline">
        <ul>
            <li>
                <a class="btn btn-sm btn-primary" asp-controller="Ticket" asp-action="AddTicket">@SharedLocalizer["ПродатьБилет"]</a>
            </li>
        </ul>
    </div>
</body>
</html>