ReSalingTickets/src/ReSalingTickets.Presentation/ViewModels/AddVenuesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ReSalingTickets.Presentation.Models;
using System.Collections.Generic;

namespace ReSalingTickets.Presentation.ViewModels
{
    public class AddVenuesViewModel
    {
        public VenueModel venueModel { get; set; }

        public IEnumerable <SelectListItem> Cities { get; set; }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/VenueController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.ViewModels;
using System.Collections.Generic;
using System.Linq;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ReSalingTickets.Presentation.Controllers
{
    public class VenueController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _resourcelocalizer;
        private IVenueService _venueRepository;
        private ICityService _cityRepository;
        private readonly IMapper _mapper;

        public VenueController(IMapper mapper,
             IServiceFactory serviceFactory,
             IStringLocalizer<SharedResource> resourcelocalizer)
        {
            _mapper = mapper;
            _resourcelocalizer = resourcelocalizer;
            _venueRepository = serviceFactory.CreateVenueService();
            _cityRepository = serviceFactory.CreateCityService();

        }
        // GET: /<controller>/
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddVenue()
        {
            var model = new AddVenuesViewModel
            {
                Cities = GetAllCities()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddVenue (AddVenuesViewModel venueViewModel)
        {
            if (ModelState.IsValid)
            {
                _venueRepository.AddVenue(_mapper.Map<Business.Entities.VenueDTO>(venueViewModel.venueModel));
                return RedirectToAction("Index", "Home");
            }
            else
            {
                    var model = new AddVenuesViewModel
                    {
                        Cities = GetAllCities(),
                        venueModel = venueViewModel.venueModel
                    };

                    return View(model);
            }
        }

        public IEnumerable<SelectListItem> GetAllCities()
        {
            var items = _cityRepository.GetAllСities();

            var cities = items
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });

            return cities;
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Views/Venue/AddVenue.cshtml
@model ReSalingTickets.Presentation.ViewModels.AddVenuesViewModel
<title>@ViewData["Title"] - ReSalingTickets</title>

@using (Html.BeginForm("AddVenue", "Venue", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.venueModel.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.venueModel.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.venueModel.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.venueModel.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.venueModel.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.venueModel.Adress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.venueModel.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.venueModel.CityId, Model.Cities)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}