ReSalingTickets/src/ReSalingTickets.Presentation/ViewModels/AddTicketsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ReSalingTickets.Presentation.Models;
using System.Collections.Generic;

namespace ReSalingTickets.Presentation.ViewModels
{
    public class AddTicketsViewModel
    {
        public TicketModel Ticket { get; set; }

        public IEnumerable<SelectListItem> Events { get; set; }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Controllers/TicketController.cs
using Autofac;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;
using ReSalingTickets.Business.Entities;
using ReSalingTickets.Business.Services.Interfaces;
using ReSalingTickets.Presentation.Infrastructure.Interfaces;
using ReSalingTickets.Presentation.Models;
using ReSalingTickets.Presentation.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ReSalingTickets.Presentation.Controllers
{
    public class TicketController : Controller
    {
        private readonly IStringLocalizer<SharedResource> _Resourcelocalizer;
        private ITicketService _ticketService;
        private IEventService _eventService;
        private readonly IMapper _mapper;

        public TicketController(IOptions<PathModel> options,
            IComponentContext componentContext,
            IStringLocalizer<SharedResource> Resourcelocalizer,
            IServiceFactory serviceFactory,
            IMapper mapper)
        {
            _mapper = mapper;
            _Resourcelocalizer = Resourcelocalizer;
            _ticketService = serviceFactory.CreateTicketService();
            _eventService = serviceFactory.CreateEventService();
        }
        
        
        public IActionResult GetllAvailableTickets(Guid id)
        {
            var tickets = _mapper.Map<List<TicketShowModel>>(_ticketService.GetAvilableTickets(id));
            if (tickets.Count() != 0)
            {
                ViewBag.image = tickets[0].PathToTheBanner;
                ViewBag.Description = tickets[0].EventDescription;
            }

            return View(tickets);
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult AddTicket()
        {
            var model = new AddTicketsViewModel
                            {
                                Events = GetEventSelectList()
                            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddTicket(AddTicketsViewModel ticketModel)
        {
            if (ModelState.IsValid)
            {
                var userLogin = User.Identity.Name;

                _ticketService.AddTicket(_mapper.Map<TicketDTO>(ticketModel.Ticket), userLogin);
                return RedirectToAction("UserPanel", "User");
            }
            else
            {
                var model = new AddTicketsViewModel
                {
                    Events = GetEventSelectList(),
                    Ticket = ticketModel.Ticket
                };

                return View(model);
            }
        }
        
        [Authorize]
        public void Delete(int id)
        {
        }

        public IEnumerable<SelectListItem> GetEventSelectList()
        {
            var items = _eventService.GetAllEvent();

            var events = items
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });

            return events;
        }
    }
}

ReSalingTickets/src/ReSalingTickets.Presentation/Views/Ticket/AddTicket.cshtml
@model ReSalingTickets.Presentation.ViewModels.AddTicketsViewModel
<title>@ViewData["Title"] - ReSalingTickets</title>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<form asp-action="AddTicket" method="post" asp-controller="Ticket">
    <div asp-validation-summary="All" class="text-danger"></div>
    
    <div class="form-group">
        <label asp-for="Ticket.Price" class="control-label">@SharedLocalizer["Цена"]</label>
        <input asp-for="Ticket.Price" type="number"/>
    </div>
    <div class="form-group">
        <select class="btn btn-success" asp-for="Ticket.EventId"
                asp-items="Model.Events" asp->
            <option>@SharedLocalizer["Событие"]</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value=@SharedLocalizer["Сохранить"] class="btn btn-default" />
    </div>
</form>

ReSalingTickets/src/ReSalingTickets.Presentation/Views/Ticket/GetllAvailableTickets.cshtml
@model IEnumerable<ReSalingTickets.Presentation.Models.TicketShowModel>
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    var claimsIdentity = User.Identity as ClaimsIdentity;
}
@{
    ViewBag.Title = "Список доступных билетов";
}
<head>
    <img src="@ViewBag.image" width="500" height="300">
    <link rel="import" href="@ViewBag.Description">
</head>

<body>
    <h3>Список доступных билетов</h3>
    <script>
        var link = document.querySelector('link[rel=import]');
        var content = link.import.querySelector('#intro-dm');
        document.body.appendChild(content.cloneNode(true));
    </script>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameSeller)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.RouteLink(item.NameSeller, new { controller = "User", action = "Contact", area = "", @item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-controller="Order" asp-action="AddOrder" asp-route-id="@item.Id">@SharedLocalizer["Выкупить"]</a>
                </td>
           </tr>
        }

    </table>
</body>